site:
  title: Testing Docs Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://antora.gitlab.io/demo/docs-site
  start_page: testing-docs::cypress-edu-path-by-filip.adoc
content:
  sources:
  # - url: https://gitlab.com/antora/demo/demo-component-a.git
  - url: ../demo-component-a  
    branches: HEAD
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    edit_url: false
  # - url: https://gitlab.com/antora/demo/demo-component-b.git
  - url: ../demo-component-b
    branches: [main, v2.0, v1.0]
    start_path: docs
  - url: ./
    branches: HEAD
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
