name: Antora Documantation Build Site

on:
  push:
    branches: 
      - master
env:
  SITE_DIR: 'docs'
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
         antora_playbook: antora-playbook.yml
      # - name: "List folder"
      #   run: |
      #      ls -ltr $GITHUB_WORKSPACE/build/site
      - name: "Upload generated site"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
